service: nintex-service

plugins:
  - serverless-pseudo-parameters # Read the region and accout id
  - serverless-iam-roles-per-function # Set up IAM role for each function
  - serverless-plugin-tracing # Integrate the X-Ray
  - serverless-plugin-canary-deployments
  - serverless-plugin-aws-alerts # Automatically generate alerts (Could be used for stopping and rolling back a canary deployment)
  - serverless-prune-plugin

custom: # stage and logLevel for log function
  stage: ${opt:stage, self:provider.stage} # use stage or get if from the provider.stage. The second paramter is default
  logLevel:
    prod: WARN
    default: DEBUG
  serverless-iam-roles-per-function:
    defaultInherit: true # All function will inherit from the provider's IAM role.
  prune:
    automatic: true
    number: 10
  # Use the serverless-plugin-aws-alerts to generate alarms in order to tragge a roll back for a canary deployment
  # alerts:
  #   stages:
  #     - production
  #     - staging
  #     - dev
  # alarms:
  #   - functionThrottles
  #   - functionErrors
  # dashboards: false

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  profile: nintex
  tracing: true # Use the serverless-plugin-tracing plugin to enable the X-Ray
  environment:
    log_level: ${self:custom.logLevel.${self:custom.stage}, self:custom.logLevel.default} # The variable for the log function
    STAGE: ${self:custom.stage} # For DEFAULT_CONTEXT in log.js
    FUNCTION_SHIELD_TOKEN: ${ssm:/nintex/${self:custom.stage}/function_shield_token} # For using the Function Shield
    NWCWORKFLOW_TABLE: NWCWorkflow
    OFFICEWORKFLOW_TABLE: OfficeWorkflow
    FETCH_HEALTH_SCORE_Q: https://sqs.us-west-2.amazonaws.com/913532693294/Fetch_Health_Score	
  iamRoleStatements:
    - Effect: Allow
      Action: cloudwatch:PutMetricData
      Resource: '*'
    - Effect: Allow # Give the permission to operate the X-Ray 
      Action: 
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'
    - Effect: Allow # Give the permission to deploy (For using canary deployment plugin)
      Action:
        - codedeploy:*
      Resource:
        - '*'
    # Give the function permission to read paramters from the EC2 Parameter Store
    - Effect: Allow
      Action: ssm:GetParameters*
      Resource: arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/nintex/${self:custom.stage}/*
    
    #  # Give the function permission to use layers (Do not really need it)
    # - Effect: Allow
    #   Action: lambda:GetLayerVersion
    #   Resource: '*'

package:
  exclude:
    - coverage/**
    - __tests__/**
    - build*
    - Information.txt
    - Database.sql
    - README.md

functions:
  # Did not follow the Rest rule to use a get request since the api could get
  # several hundreds of 37 bytes long ids from the front end.
  # The Lambda function has a limitation for any synchoronous call (6MB payload). But it should be large enough for this.
  fetch-nwc-workflows:
    handler: functions/fetch-nwc-workflows.handler
    events:
      - http:
          path: /nwcworkflows
          method: post
          cors: true
    memorySize: 256
    environment:
      async_metrics: true # Use this variable to control whether send the metrics to CloudWatch Async
    layers:
      - ${cf:lambda-layers-dev.NintexDependenciesLayerExport}

  add-nwc-workflows:
    handler: functions/add-nwc-workflows.handler
    events:
      - http:
          path: /nwcworkflow
          method: post
          cors: true
    memorySize: 256
    environment:
      async_metrics: true
      SQS_BATCH_NUM: 10
      MESSAGE_DELAY_SECOND: 20
    iamRoleStatements:
      # Give the function permission to put message to SQS
      - Effect: Allow
        Action: sqs:SendMessage
        Resource: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:Fetch_Health_Score
    layers:
      - ${cf:lambda-layers-dev.NintexDependenciesLayerExport}

  fetch-nwc-health-score:
      handler: functions/fetch-nwc-health-score.handler
      events:
        - sqs: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:Fetch_Health_Score
      memorySize: 256
      timeout: 40
      environment:
        async_metrics: true
        NWC_LIST_WORKFLOWS_API: https://us.nintex.io/workflows/v1/designs
      iamRoleStatements:
        # Give the function permission to receive, getQueueAtrributes and delete message from SQS
        - Effect: Allow
          Action: sqs:ReceiveMessage
          Resource: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:Fetch_Health_Score
        - Effect: Allow
          Action: sqs:DeleteMessage
          Resource: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:Fetch_Health_Score
        - Effect: Allow
          Action: sqs:GetQueueAttributes
          Resource: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:Fetch_Health_Score
      layers:
        - ${cf:lambda-layers-dev.NintexDependenciesLayerExport}
